--RP the application installation should do this for you in the Supporting Objects...
CREATE TABLE "BIP2FOP" 
   (	"ID" NUMBER, 
	"IN_BIP" "XMLTYPE", 
	"OUT_FOP" "XMLTYPE", 
	"TEMPLATE_NAME" VARCHAR2(200), 
	"NOTES" VARCHAR2(1000), 
	"MODIFIED" DATE, 
	"LAYOUT_ID" NUMBER, 
	"MODIFIED_BY" VARCHAR2(50), 
	"REPORT_QUERY_ID" NUMBER, 
	"WORD_SOURCE" BLOB, 
	"WORD_SOURCE_MODIFIED" TIMESTAMP (6), 
	"WORD_SOURCE_FILENAME" VARCHAR2(100), 
	 CONSTRAINT "BIP2FOP_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

 CREATE SEQUENCE  "BIP2FOP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE ;

CREATE OR REPLACE TRIGGER "BI_BIP2FOP" BEFORE
    INSERT ON "BIP2FOP"
    FOR EACH ROW
BEGIN
    IF inserting THEN
        IF :new."ID" IS NULL THEN
            SELECT
                BIP2FOP_SEQ.nextval
            INTO :new."ID"
            FROM
                dual;

        END IF;


        IF :new."MODIFIED" IS NULL THEN
            :new.MODIFIED := sysdate;
        END IF;

        IF :NEW."MODIFIED_BY" IS NULL THEN
            :new.modified_by    := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER);
        END IF;

    END IF;
END;

/


ALTER TRIGGER "BI_BIP2FOP" ENABLE;

CREATE OR REPLACE TRIGGER "BU_BIP2FOP" 
BEFORE UPDATE ON "BIP2FOP" FOR EACH ROW 

BEGIN
    :new.MODIFIED := sysdate;
    :new.modified_by := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),user);
END;

/


ALTER TRIGGER "BU_BIP2FOP" ENABLE;

CREATE UNIQUE INDEX "BIP2FOP_PK" ON "BIP2FOP" ("ID") 
  ;


